language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/setup-oracle-jdk7.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/build-nablarch.sh -p ci
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: iHePvqPBOW0k150kQgS6Rb/m0IDgOjNzixz3hNJ8v/uRtCYW8Fqq+Nl2g1BhsDjMQaPc2InnBH5OknfFLvuMNqVuPisKWN2U/0B6lT5IoFIIwFpCviEJ0HcLbTnihGk292jHAoxbdCIxy6Vvn5XT5UZLiHGxBhUPIoSz8nDAQA01NvsAAJ61GS+mkBG758Gq4EmgiCgMBp22ICZNfO7fMfAdK8Lz+f/onD2v/WeMeKunsL8LazbkrbbxGM3MtSvurJi7ASKFp019l+Piko3lBPLxfhmJDktoP7Ewzw5RjjxnCE5ne3Xtlso3IqYw441VNFRI4LjaIviCYvYxZ0q3EFRUD6eGrgPfcbozsXEMrGTPySPYbM+8cWbzhV9/KrwDcfAicb9XXor1eHAVd59v0gSnrqG/8EE5ouG4VAvf2bTNJ+W800sllkTdO/Zlf745FhRMnRvxhz3911ny1H7Oqkjok+in/3GVFGUrv7Zlbo7bn87ODDoXfxUpQojkuDfnPnbZwlesUsICs3JaC7kDOpfpuUwbk0jQJ/2Zc4s2vGDDSac1jD20o84yzqVnEIXMjWklZuNADFEoRle7HVznqM97qUCAQ72LZVJepg/O8mSbmNAyk67Enkksnk5EBhd+dVBWnVisQlYQpnVTR38Dh4ukiNGJnXUOGZ5N41DNPdg=
